### ISSUE TITLE
Failure in Jest Tests

### ISSUE THREAD

**Issue by cuff-links** [mwinteringham/restful-booker-platform#117] opened 2019-12-09 01:56 UTC
Environment:
OS: Mac OSX 10.14.6

When I run the `build_locally.sh` file, I get failures in the jest tests. Here is some of the output:

```
 PASS  tests/welcome-test.js

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "FetchError {
      message:
       'invalid json response body at http://localhost/branding/ reason: Unexpected token < in JSON at position 0',
      type: 'invalid-json' }".

      64 |                         <div className='col-sm-1'></div>
      65 |                         <div className='col-sm-10'>
    > 66 |                             <h2>Rooms</h2>
         |                        ^
      67 |                         </div>
      68 |                         <div className='col-sm-1'></div>
      69 |                     </div>

      at BufferedConsole.log (node_modules/@jest/console/build/BufferedConsole.js:199:10)
      at src/js/components/Home.jsx:66:24

 PASS  tests/login-test.js

Test Suites: 1 failed, 14 passed, 15 total
Tests:       1 failed, 37 passed, 38 total
Snapshots:   29 passed, 29 total
Time:        7.677s
Ran all test suites.

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "FetchError {
      message:
       'invalid json response body at http://localhost/room/ reason: Unexpected token < in JSON at position 0',
      type: 'invalid-json' }".

      79 |                 </div>
      80 |             </div>
    > 81 |         );
         |                     ^
      82 |     }
      83 | }
      84 | 

      at BufferedConsole.log (node_modules/@jest/console/build/BufferedConsole.js:199:10)
      at src/js/components/Home.jsx:81:24

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui@4.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ui@4.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by cuff-links** [comment] 2019-12-09 01:59
[2019-12-09T01_49_51_948Z-debug.log](https://github.com/mwinteringham/restful-booker-platform/files/3937567/2019-12-09T01_49_51_948Z-debug.log)

**Comment by mwinteringham** [comment] 2020-05-04 19:05
@cuff-links is this still reproducible and if so can you give me complete output from the console as it's hard to tell what check is failing at the moment.

Going to close this until you tell me otherwise as I'm unable to reproduce the error.

**Closed by mwinteringham** 2020-05-04 19:05 UTC
