### ISSUE TITLE
CreateBooking API - Booking the same room (roomid) at the same date range

### ISSUE THREAD

**Issue by sobky** [mwinteringham/restful-booker-platform#114] opened 2019-11-23 19:22 UTC
It only happens when adding the same bookingid in both requests

**Comment by mwinteringham** [comment] 2020-05-04 19:06
@sobky going to need more information on this for me to look into it. Closing for now, but feel free to add more details around what the issue is.

**Closed by mwinteringham** 2020-05-04 19:06 UTC
